name: Publish Published Version to npm

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-devpublish-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-devpublish-
      
      - name: Install Pacakges
        run: yarn install --frozen-lockfile

      - name: Setup Git
        run: git config --global user.name "${{ GITHUB_ACTOR }}"
        run: git config --global user.email "${{ GITHUB_ACTOR }}@users.noreply.github.com"

      - name: Change Version
        run: npm version ${{ github.event.release.tag_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: npm publish --tag ${{ github.event.release.target_commitish }} || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: Git Push Repo
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}